image: ruby:2.6.2

variables:
  RACK_ENV: "test"

stages:
  - init
  - test

install:
  stage: init
  script:
    - bundle install --path .bundle
  artifacts:
    paths:
    - .bundle/
    -  Gemfile.lock

rspec:
  stage: test
  script:
    - bundle exec rspec spec/lib
  dependencies:
    - install
