image: ruby:2.6.2

variables:
  CAP_USER: "deployer"
  BUNDLE_CACHE: "vendor/bundle/"
  RAILS_ENV: "test"

stages:
  - test

rspec:
  stage: test
  script:
    -  bundle install
    -  bundle exec rspec spec/lib
