version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.2

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: run tests
          command: |
            bundle exec rspec spec/lib
  unko:
    docker:
      - image: ubuntu:16.04

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: put unko
          command: |
            echo 'うんこ〜〜〜〜〜〜〜〜〜!!'

workflows:
  version: 2

  deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - unko:
          filters:
            branches:
              only:
                - test


